// src/webviews/components/Sidebar.svelte
<script lang="ts">
    
    // @ts-nocheck
    
    import { onMount } from 'svelte';
    import ShowIcon from './ShowIcon.svelte';
    import HideIcon from './HideIcon.svelte';
    import History from './History.svelte';
    import BracketMenu from './BracketMenu.svelte';
    import SettingsMenu from './SettingsMenu.svelte';
    import Loading from './Loading.svelte';
   
    let initialView:string = 'default';
    let isLoading:boolean = false;
    let environment:string = '';
    let componentSelected:svelteHTML = ShowIcon;
    let isProphetInstalled:boolean;
    let isToShowDevBuildBtn:boolean;
    let textCommandDevBuildBtn:string;
    let textLayoutDevBuildBtn:string;
    let isToShowPrdBuildBtn:boolean;
    let textCommandPrdBuildBtn:string;
    let textLayoutPrdBuildBtn:string;
    let codeversionConstant:string;
    let hostnameConstant:string;
    let codeversionPropertyShort:string;
    let hostnamePropertyShort:string;
    let isPasswordVisible:boolean = false;   
    let page: "bracket" | "settings" = tsvscode.getState()?.page || "bracket";

    $: {
        tsvscode.setState({ page });
    }
    
    onMount(() => {
        window.addEventListener('message', (event) => {
            const message = event.data; 
            switch (message.command) {
                case 'initialView': {
                    initialView = message.data;

                    if (initialView === 'checkWorkspace') {
                        tsvscode.postMessage({
                            type: 'onCheckWorkspace',
                            value: true
                        });
                    }
                                        
                    if (initialView === 'default') {
                        updateMarginTopMain(true);
                    } else {
                        updateMarginTopMain(false);
                    }     
                    
                    if (initialView === 'default' && page === "settings") {
                        updateClass('.settings', '.bracket');
                    }   

                    break;
                }

                case 'jsonValues': {
                    if (page === "bracket") {
                        const jsonValues = message.data;
    
                        document.getElementById('hostname').value = jsonValues.hostname;
                        document.getElementById('userName').value = jsonValues.username;
                        document.getElementById('password').value = jsonValues.password;
                        document.getElementById('codeVersion').value = jsonValues.codeversion;
                    }
                    
                    break;
                }      
                
                case 'loading': {
                    [isLoading, environment] = message.data;
                    
                    break;
                }  
            }
        });  

        if (initialView === 'default' && page === "settings") {
            updateClass('.settings', '.bracket');
        }        
        
        isProphetInstalled = isProphetInstall;
        isToShowDevBuildBtn = showDevBuildBtn;
        textCommandDevBuildBtn = commandDevBuildBtn;
        isToShowPrdBuildBtn = showPrdBuildBtn 
        textCommandPrdBuildBtn = commandPrdBuildBtn;
        textLayoutDevBuildBtn = textDevBuildBtn;
        textLayoutPrdBuildBtn = textPrdBuildBtn;
        codeversionConstant = codeversion;
        hostnameConstant = hostname;
        codeversionPropertyShort = codeversionHistoryPropertyShort;
        hostnamePropertyShort = hostnameHistoryPropertyShort;
    }
    );
    
    const changeJsonFile = () => {
        const hostname:string = document.getElementById('hostname')?.value;
        const username:string = document.getElementById('userName')?.value;
        const password:string = document.getElementById('password')?.value;
        const codeversion:string = document.getElementById('codeVersion')?.value;

        const jsonContent = {
            "hostname": hostname,
            "username": username,
            "password": password,
            "code-version": codeversion
        };
        
        tsvscode.postMessage({
            type: 'onChangeFile',
            value: jsonContent
        });
    }

    const clickBtnCleanUpload = () => {
        tsvscode.postMessage({
            type: 'onCleanUpload',
            value: true
        });
    }

    const clickBtnDisableUpload = () => {
        tsvscode.postMessage({
            type: 'onDisableUpload',
            value: true
        });
    }

    const clickBtnEnableUpload = () => {
        tsvscode.postMessage({
            type: 'onEnableUpload',
            value: true
        });
    }

    const clickBtnNewCodeversion = () => {
        tsvscode.postMessage({
            type: 'onNewCodeversion',
            value: true
        });
    }

    const clickBtnDeleteCodeversion = () => {
        tsvscode.postMessage({
            type: 'onDeleteCodeversion',
            value: true
        });
    }

    const clickBtnBuild = (option) => {
        tsvscode.postMessage({
            type: 'onBuild',
            value: option
        });
    }

    const changeProperty = (input:string, property:string) => {        
        tsvscode.postMessage({
            type: 'onChangeProperty',
            value: [input, property]
        });
    }

    const clickBtnHistory = (property:string) => {
        tsvscode.postMessage({
            type: 'onShowQuickPick',
            value: property
        });
    }

    const getInputData = () => {
        tsvscode.postMessage({
            type: 'onGetInputData',
            value: true
        });
    }

    const clickBtnLink = (isBusinessManager) => {
        tsvscode.postMessage({
            type: 'onBtnLink',
            value: [document.getElementById('hostname')?.value, isBusinessManager]
        });
    }

    const clickBtnOpenSettings = () => {
        tsvscode.postMessage({
            type: 'onOpenSettings',
            value: true
        });
    }    
    
    const buttonClick = () => {
        isPasswordVisible = !isPasswordVisible;
        componentSelected = isPasswordVisible ? HideIcon : ShowIcon;
    }

    const updateClass = (classNameAdd, classNameRemove) => {
        const elementToAdd = document.querySelector(classNameAdd);
        elementToAdd.classList.add('selected');
        const elementToRemove = document.querySelector(classNameRemove);
        elementToRemove.classList.remove('selected');
    }

    const updateMarginTopMain = (isDefault) => {
        const mainElement = document.getElementById('main');
        
        if (isDefault) {
            mainElement?.style.marginTop = '45px';
        } else {
            mainElement?.style.marginTop = '5px';
        }
    }
    
</script>

<style>
    :global(body) {
        font-family: var(--vscode-font-family);
        font-size: 13px;
        padding-right: 20px;
        overflow-x: hidden;
    }

    input {
        color: var(--vscode-input-foreground);
        background-color: inherit;
        border: 1px solid var(--vscode-input-border, transparent);
        background-color: var(--vscode-input-background);
        height: 24px;
    }

    input:focus{
        outline-offset: -1px;
        outline-color: var(--vscode-input-foreground);
    }

    button {
        color: var(--vscode-button-foreground); 
        background-color: var(--vscode-button-background);
        border: 1px solid var(--vscode-button-border,transparent);
        cursor: pointer;
        box-sizing: border-box;  
        height: 28px;
    }

    button:hover {
        background-color: var(--vscode-button-hoverBackground);
    }

    button:focus {
      outline: none;
  }
    
    div#main{
       min-width: 315px;
       margin-top: 45px;

    }
    #hostname {
       margin-bottom: 10px; 
       width: 100%;
       width: 285px;
       margin-top: 10px;
       font-family: var(--vscode-font-family);
    }
    #codeVersion {
       margin-bottom: 10px; 
       width: 100%;
       width: 285px;
       margin-top: 10px;
       font-family: var(--vscode-font-family);
    }
    #userName {
       margin-bottom: 10px; 
       width: 100%;
       width: 285px; 
       margin-top: 10px;
       font-family: var(--vscode-font-family);
    }
    #password {
       margin-bottom: 10px; 
       width: 100%;
       width: 285px;
       margin-top: 10px;
       font-family: var(--vscode-font-family);
    }
    
    #btnSvgPassword {
       width: 28px;
       height: 28px;
       left: 310px;
       position: absolute;
       color: var(--vscode-input-foreground);
       background-color: transparent;
       border: none;
       margin-top: 10px;
    }

    #btnSvgPassword:hover {
        background-color: transparent;
    }

    #btnSvgHostname {
       width: 28px;
       height: 28px;
       left: 310px;
       position: absolute;
       color: var(--vscode-input-foreground);
       background-color: transparent;
       border: none;
       margin-top: 10px;
    }

    .svgLoading {
       width: 50px;
       height: 50px;  
       left: 132.5px; /* Min-width divided per two and minus half of element width */
       position: relative;
       top: 70px;
    }

    #btnSvgHostname:hover {
        background-color: transparent;
    }

    #btnSvgCodeversion {
       width: 28px;
       height: 28px;
       left: 310px;
       position: absolute;
       color: var(--vscode-input-foreground);
       background-color: transparent;
       border: none;
       margin-top: 10px;
    }

    #btnSvgCodeversion:hover {
        background-color: transparent;
    }

    .btns-block {
        margin-bottom: 10px; 
    }

    .environmentSettings {
        margin-bottom: 10px; 
    }

    .btn {
        width: 100%;
        width: 315px;
        margin-top: 10px;
        font-family: var(--vscode-font-family);
    }

    .textInput, .textButton {
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
        padding: 4px 0 0;
        margin: 0;
        font-size: 13px;
        font-weight: 400;
        font-family: var(--vscode-font-family);
    }

    #btnCreate, #btnFix {
       margin-top: 20px; 
       width: 100%;
    }

    .buttons-wrapper {
        height: 45px;
        display: flex;
        width: 315px;
        position: fixed;
        top: 0;
        z-index: 999;
        background-color: var(--vscode-sideBar-background);
    }

    .menu-button {
        width: 50%;
        padding: 0;
        color: rgb(92, 92, 92);
        background-color: transparent;
        height: 32px;
        border: none;
    }

    .menu-button:hover {
        background-color: transparent;
    }

    .selected {
        color: var(--vscode-input-foreground);
    }

    .loading {
        position: absolute;
        width: 315px;
        text-align: center;
        display: flex;
        align-content: center;
        justify-content: center;
        align-items: center;
        font-weight: 400;
        font-size: 14px;
        margin-top: 20px;
    }

    .message-text {
        font-weight: 400;
        font-size: 14px;
    }

    .d-none {
        display: none;
    }

</style>    

{#if initialView === 'default'}
    <div class="buttons-wrapper">
        <button class="menu-button selected bracket" on:click={() => { 
            page = 'bracket';
            getInputData();
            updateClass('.bracket', '.settings');
            }}>
            <BracketMenu/>
        </button> 
        <button class="menu-button settings" on:click={() => { 
            page = 'settings';
            updateClass('.settings', '.bracket');
            }}>
            <SettingsMenu/>
        </button> 
    </div>
{/if}

<div id="main">

    {#if initialView === 'default'}

        {#if isLoading}
            <div class="loading-wrapper">
                <div class='loading'> 
                    Connecting with {environment}...
                </div>
                <div class="svgLoading">
                    <Loading/>
                </div>
            </div>
        {/if}

        {#if page === 'bracket'}
            <div class="environmentSettings {isLoading ? 'd-none' : ''}">
                <div>
                    <div class="textInput">Hostname</div>
                    <input on:change={(e)=>{
                        changeProperty(e.target.value, hostnamePropertyShort);
                        changeJsonFile();
                    }} type="text" id="hostname">
            
                    <button id="btnSvgHostname" on:click={()=>{
                        clickBtnHistory(hostnameConstant);
                    }}><svelte:component this={History} /></button>  
            
                </div>
            
                <div>
                    <div class="textInput">Code Version</div>
                    <input on:change={(e)=>{
                        changeProperty(e.target.value, codeversionPropertyShort);
                        changeJsonFile();
                    }} type="text" id="codeVersion">
                            
                    <button id="btnSvgCodeversion" on:click={()=>{
                        clickBtnHistory(codeversionConstant);
                    }}><svelte:component this={History} /></button>  
            
                </div>
            
                <div class="textInput">User Name</div>
                <input on:change={()=>{
                    changeJsonFile();
                }} type="text" id="userName">
            
                <div>
                    <div class="textInput">Password</div>
                    <input on:change={()=>{
                        changeJsonFile();
                    }} type={isPasswordVisible ? "text" : "password"} id="password">
                
                    <button id="btnSvgPassword" on:click={()=>{
                        buttonClick()
                    }}><svelte:component this={componentSelected} /></button>            
                </div>   
            </div>

            <div class="environmentSettings {isLoading ? 'd-none' : ''}">
                <div class="textButton">Environment Links</div>
                <div>
                    <button on:click={()=>{
                        clickBtnLink(true);
                    }} class="btn monaco-button monaco-text-button">Open Business Manager</button>                    
                </div>

                <div>
                    <button on:click={()=>{
                        clickBtnLink(false);
                    }} class="btn monaco-button monaco-text-button">Open StoreFront</button>                    
                </div>
            </div>
        {/if}

        {#if page === 'settings'}    
            <div class="settings-wrapper {isLoading ? 'd-none' : ''}">
                {#if isProphetInstalled}                
                    <div class="btns-block">
                        <div class="textButton">Environment Settings</div>
                        <div>
                            <button on:click={()=>{
                                clickBtnNewCodeversion();
                            }} class="btn monaco-button monaco-text-button">New Code Version</button>                    
                        </div>
            
                        <div>
                            <button on:click={()=>{
                                clickBtnDeleteCodeversion();
                            }} class="btn monaco-button monaco-text-button">Delete Code Version</button>
                        </div>
                    </div>        
                
                    {#if isToShowDevBuildBtn || isToShowPrdBuildBtn}
                        <div class="textButton">Compiler</div>
                        <div class="btns-block">
                            {#if isToShowDevBuildBtn}
                                <div>
                                    <button on:click={()=>{
                                        clickBtnBuild(textCommandDevBuildBtn);
                                    }} class="btn monaco-button monaco-text-button">{textLayoutDevBuildBtn}</button>
                                </div>
                            {/if}

                            {#if isToShowPrdBuildBtn}
                                <div>
                                    <button on:click={()=>{
                                        clickBtnBuild(textCommandPrdBuildBtn);
                                    }} class="btn monaco-button monaco-text-button">{textLayoutPrdBuildBtn}</button>
                                </div>
                            {/if}
                        </div> 
                    {/if}           
                
                    <div class="btns-block">
                        <div class="textButton">Commands</div>
                        <div>
                            <button on:click={()=>{
                                clickBtnCleanUpload();
                            }} class="btn monaco-button monaco-text-button">Clean Project / Upload All</button>                    
                        </div>
            
                        <div>
                            <button on:click={()=>{
                                clickBtnEnableUpload();
                            }} class="btn monaco-button monaco-text-button">Enable Upload</button>
                        </div>
            
                        <div>
                            <button on:click={()=>{
                                clickBtnDisableUpload();
                            }} class="btn monaco-button monaco-text-button">Disable Upload</button>
                        </div>
                    </div>  

                    <div class="btns-block">
                        <div class="textButton">Configuration</div>
                        <div>
                            <button on:click={()=>{
                                clickBtnOpenSettings();
                            }} class="btn monaco-button monaco-text-button">Extention settings</button>                    
                        </div>
                    </div>                    
                {/if}
            </div>
        {/if}
    {/if}

    {#if initialView === 'noFile'}

        <p class="message-text">This folder do not has a dw.json file or is not a SFCC project!</p>
        <p class="message-text">If you already have a workspace open, please click on bellow button to create a new dw.json file.</p>

        <!-- svelte-ignore missing-declaration -->
        <button on:click={()=>{
            tsvscode.postMessage({
                type: 'onCreateFile',
                value: true
            });
        }} id="btnCreate" class="monaco-button monaco-text-button btn">Create a dw.json</button>

    {/if}

    {#if initialView === 'noWorkspace'}

        <p class="message-text">Ups... This extensions needs a Workspace to run...</p>
        <p class="message-text">Please open a Workspace.</p>

    {/if}

    {#if initialView === 'schemaError'}

        <p class="message-text">Detected a dw.json file with a schema error!</p>
        <p class="message-text">The properties names are incorrect or not in string format.</p>

        <!-- svelte-ignore missing-declaration -->
        <button on:click={()=>{
            tsvscode.postMessage({
                type: 'onCreateFile',
                value: false
            });
        }} id="btnFix" class="monaco-button monaco-text-button btn">Fix the dw.json</button>

    {/if}
        
</div>

// src/webviews/components/Sidebar.tsx
import React, { useState, useEffect, useRef } from 'react';
import { ShowIcon } from './ShowIcon';
import { HideIcon } from './HideIcon';
import { History } from './History';
import { BracketMenu } from './BracketMenu';
import { SettingsMenu } from './SettingsMenu';
import { Loading } from './Loading';
import './Sidebar.css';

// Use the already acquired VSCode API from the global scope
declare const tsvscode: any;
const vscode = tsvscode;

interface WindowWithGlobals extends Window {
  isProphetInstall?: boolean;
  showDevBuildBtn?: boolean;
  commandDevBuildBtn?: string;
  showPrdBuildBtn?: boolean;
  commandPrdBuildBtn?: string;
  textDevBuildBtn?: string;
  textPrdBuildBtn?: string;
  hostname?: string;
  codeversion?: string;
  hostnameHistoryPropertyShort?: string;
  codeversionHistoryPropertyShort?: string;
}

const w = window as WindowWithGlobals;

export const Sidebar: React.FC = () => {
  const [initialView, setInitialView] = useState<string>('default');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [environment, setEnvironment] = useState<string>('');
  const [isPasswordVisible, setIsPasswordVisible] = useState<boolean>(false);
  const [page, setPage] = useState<'bracket' | 'settings'>(() => {
    const state = vscode.getState();
    return state?.page || 'bracket';
  });

  const hostnameRef = useRef<HTMLInputElement>(null);
  const usernameRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);
  const codeversionRef = useRef<HTMLInputElement>(null);

  const isProphetInstalled = w.isProphetInstall || false;
  const isToShowDevBuildBtn = w.showDevBuildBtn || false;
  const textCommandDevBuildBtn = w.commandDevBuildBtn || '';
  const textLayoutDevBuildBtn = w.textDevBuildBtn || '';
  const isToShowPrdBuildBtn = w.showPrdBuildBtn || false;
  const textCommandPrdBuildBtn = w.commandPrdBuildBtn || '';
  const textLayoutPrdBuildBtn = w.textPrdBuildBtn || '';
  const codeversionConstant = w.codeversion || '';
  const hostnameConstant = w.hostname || '';
  const codeversionPropertyShort = w.codeversionHistoryPropertyShort || '';
  const hostnamePropertyShort = w.hostnameHistoryPropertyShort || '';

  useEffect(() => {
    vscode.setState({ page });
  }, [page]);

  useEffect(() => {
    const messageHandler = (event: MessageEvent) => {
      const message = event.data;
      switch (message.command) {
        case 'initialView': {
          setInitialView(message.data);

          if (message.data === 'checkWorkspace') {
            vscode.postMessage({
              type: 'onCheckWorkspace',
              value: true
            });
          }

          if (message.data === 'default') {
            updateMarginTopMain(true);
          } else {
            updateMarginTopMain(false);
          }

          if (message.data === 'default' && page === 'settings') {
            updateClass('.settings', '.bracket');
          }

          break;
        }

        case 'jsonValues': {
          if (page === 'bracket') {
            const jsonValues = message.data;

            if (hostnameRef.current) hostnameRef.current.value = jsonValues.hostname || '';
            if (usernameRef.current) usernameRef.current.value = jsonValues.username || '';
            if (passwordRef.current) passwordRef.current.value = jsonValues.password || '';
            if (codeversionRef.current) codeversionRef.current.value = jsonValues.codeversion || '';
          }

          break;
        }

        case 'loading': {
          const [loading, env] = message.data;
          setIsLoading(loading);
          setEnvironment(env);
          break;
        }
      }
    };

    window.addEventListener('message', messageHandler);

    if (initialView === 'default' && page === 'settings') {
      updateClass('.settings', '.bracket');
    }

    return () => {
      window.removeEventListener('message', messageHandler);
    };
  }, [page, initialView]);

  const changeJsonFile = () => {
    const hostname = hostnameRef.current?.value || '';
    const username = usernameRef.current?.value || '';
    const password = passwordRef.current?.value || '';
    const codeversion = codeversionRef.current?.value || '';

    const jsonContent = {
      "hostname": hostname,
      "username": username,
      "password": password,
      "code-version": codeversion
    };

    vscode.postMessage({
      type: 'onChangeFile',
      value: jsonContent
    });
  };

  const clickBtnCleanUpload = () => {
    vscode.postMessage({
      type: 'onCleanUpload',
      value: true
    });
  };

  const clickBtnDisableUpload = () => {
    vscode.postMessage({
      type: 'onDisableUpload',
      value: true
    });
  };

  const clickBtnEnableUpload = () => {
    vscode.postMessage({
      type: 'onEnableUpload',
      value: true
    });
  };

  const clickBtnNewCodeversion = () => {
    vscode.postMessage({
      type: 'onNewCodeversion',
      value: true
    });
  };

  const clickBtnDeleteCodeversion = () => {
    vscode.postMessage({
      type: 'onDeleteCodeversion',
      value: true
    });
  };

  const clickBtnBuild = (option: string) => {
    vscode.postMessage({
      type: 'onBuild',
      value: option
    });
  };

  const changeProperty = (input: string, property: string) => {
    vscode.postMessage({
      type: 'onChangeProperty',
      value: [input, property]
    });
  };

  const clickBtnHistory = (property: string) => {
    vscode.postMessage({
      type: 'onShowQuickPick',
      value: property
    });
  };

  const getInputData = () => {
    vscode.postMessage({
      type: 'onGetInputData',
      value: true
    });
  };

  const clickBtnLink = (isBusinessManager: boolean) => {
    vscode.postMessage({
      type: 'onBtnLink',
      value: [hostnameRef.current?.value || '', isBusinessManager]
    });
  };

  const clickBtnOpenSettings = () => {
    vscode.postMessage({
      type: 'onOpenSettings',
      value: true
    });
  };

  const buttonClick = () => {
    setIsPasswordVisible(!isPasswordVisible);
  };

  const updateClass = (classNameAdd: string, classNameRemove: string) => {
    const elementToAdd = document.querySelector(classNameAdd);
    elementToAdd?.classList.add('selected');
    const elementToRemove = document.querySelector(classNameRemove);
    elementToRemove?.classList.remove('selected');
  };

  const updateMarginTopMain = (isDefault: boolean) => {
    const mainElement = document.getElementById('main');
    if (mainElement) {
      mainElement.style.marginTop = isDefault ? '45px' : '5px';
    }
  };

  return (
    <>
      {initialView === 'default' && (
        <div className="buttons-wrapper">
          <button
            className="menu-button selected bracket"
            onClick={() => {
              setPage('bracket');
              getInputData();
              updateClass('.bracket', '.settings');
            }}
          >
            <BracketMenu />
          </button>
          <button
            className="menu-button settings"
            onClick={() => {
              setPage('settings');
              updateClass('.settings', '.bracket');
            }}
          >
            <SettingsMenu />
          </button>
        </div>
      )}

      <div id="main">
        {initialView === 'default' && (
          <>
            {isLoading && (
              <div className="loading-wrapper">
                <div className='loading'>
                  Connecting with {environment}...
                </div>
                <div className="svgLoading">
                  <Loading />
                </div>
              </div>
            )}

            {page === 'bracket' && (
              <div className={`environmentSettings ${isLoading ? 'd-none' : ''}`}>
                <div>
                  <div className="textInput">Hostname</div>
                  <input
                    type="text"
                    id="hostname"
                    ref={hostnameRef}
                    onChange={(e) => {
                      changeProperty(e.target.value, hostnamePropertyShort);
                      changeJsonFile();
                    }}
                  />
                  <button
                    id="btnSvgHostname"
                    onClick={() => {
                      clickBtnHistory(hostnameConstant);
                    }}
                  >
                    <History />
                  </button>
                </div>

                <div>
                  <div className="textInput">Code Version</div>
                  <input
                    type="text"
                    id="codeVersion"
                    ref={codeversionRef}
                    onChange={(e) => {
                      changeProperty(e.target.value, codeversionPropertyShort);
                      changeJsonFile();
                    }}
                  />
                  <button
                    id="btnSvgCodeversion"
                    onClick={() => {
                      clickBtnHistory(codeversionConstant);
                    }}
                  >
                    <History />
                  </button>
                </div>

                <div className="textInput">User Name</div>
                <input
                  type="text"
                  id="userName"
                  ref={usernameRef}
                  onChange={() => {
                    changeJsonFile();
                  }}
                />

                <div>
                  <div className="textInput">Password</div>
                  <input
                    type={isPasswordVisible ? "text" : "password"}
                    id="password"
                    ref={passwordRef}
                    onChange={() => {
                      changeJsonFile();
                    }}
                  />
                  <button
                    id="btnSvgPassword"
                    onClick={() => {
                      buttonClick();
                    }}
                  >
                    {isPasswordVisible ? <HideIcon /> : <ShowIcon />}
                  </button>
                </div>
              </div>
            )}

            {page === 'bracket' && (
              <div className={`environmentSettings ${isLoading ? 'd-none' : ''}`}>
                <div className="textButton">Environment Links</div>
                <div>
                  <button
                    onClick={() => {
                      clickBtnLink(true);
                    }}
                    className="btn"
                  >
                    Open Business Manager
                  </button>
                </div>

                <div>
                  <button
                    onClick={() => {
                      clickBtnLink(false);
                    }}
                    className="btn"
                  >
                    Open StoreFront
                  </button>
                </div>
              </div>
            )}

            {page === 'settings' && (
              <div className={`settings-wrapper ${isLoading ? 'd-none' : ''}`}>
                {isProphetInstalled && (
                  <>
                    <div className="btns-block">
                      <div className="textButton">Environment Settings</div>
                      <div>
                        <button
                          onClick={() => {
                            clickBtnNewCodeversion();
                          }}
                          className="btn"
                        >
                          New Code Version
                        </button>
                      </div>

                      <div>
                        <button
                          onClick={() => {
                            clickBtnDeleteCodeversion();
                          }}
                          className="btn"
                        >
                          Delete Code Version
                        </button>
                      </div>
                    </div>

                    {(isToShowDevBuildBtn || isToShowPrdBuildBtn) && (
                      <>
                        <div className="textButton">Compiler</div>
                        <div className="btns-block">
                          {isToShowDevBuildBtn && (
                            <div>
                              <button
                                onClick={() => {
                                  clickBtnBuild(textCommandDevBuildBtn);
                                }}
                                className="btn"
                              >
                                {textLayoutDevBuildBtn}
                              </button>
                            </div>
                          )}

                          {isToShowPrdBuildBtn && (
                            <div>
                              <button
                                onClick={() => {
                                  clickBtnBuild(textCommandPrdBuildBtn);
                                }}
                                className="btn"
                              >
                                {textLayoutPrdBuildBtn}
                              </button>
                            </div>
                          )}
                        </div>
                      </>
                    )}

                    <div className="btns-block">
                      <div className="textButton">Commands</div>
                      <div>
                        <button
                          onClick={() => {
                            clickBtnCleanUpload();
                          }}
                          className="btn"
                        >
                          Clean Project / Upload All
                        </button>
                      </div>

                      <div>
                        <button
                          onClick={() => {
                            clickBtnEnableUpload();
                          }}
                          className="btn"
                        >
                          Enable Upload
                        </button>
                      </div>

                      <div>
                        <button
                          onClick={() => {
                            clickBtnDisableUpload();
                          }}
                          className="btn"
                        >
                          Disable Upload
                        </button>
                      </div>
                    </div>

                    <div className="btns-block">
                      <div className="textButton">Configuration</div>
                      <div>
                        <button
                          onClick={() => {
                            clickBtnOpenSettings();
                          }}
                          className="btn"
                        >
                          Extension settings
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </div>
            )}
          </>
        )}

        {initialView === 'noFile' && (
          <>
            <p className="message-text">This folder do not has a dw.json file or is not a SFCC project!</p>
            <p className="message-text">If you already have a workspace open, please click on bellow button to create a new dw.json file.</p>

            <button
              onClick={() => {
                vscode.postMessage({
                  type: 'onCreateFile',
                  value: true
                });
              }}
              id="btnCreate"
              className="btn"
            >
              Create a dw.json
            </button>
          </>
        )}

        {initialView === 'noWorkspace' && (
          <>
            <p className="message-text">Ups... This extensions needs a Workspace to run...</p>
            <p className="message-text">Please open a Workspace.</p>
          </>
        )}

        {initialView === 'schemaError' && (
          <>
            <p className="message-text">Detected a dw.json file with a schema error!</p>
            <p className="message-text">The properties names are incorrect or not in string format.</p>

            <button
              onClick={() => {
                vscode.postMessage({
                  type: 'onCreateFile',
                  value: false
                });
              }}
              id="btnFix"
              className="btn"
            >
              Fix the dw.json
            </button>
          </>
        )}
      </div>
    </>
  );
};
